version: '3'

volumes:
  postgres_data:
    driver: local

services:
  person-management-db:
    image: postgres:14.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: person-management
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    restart: always
    expose:
      - 5432
    ports:
      - "5432:5432"
