server:
  port: 8080
  servlet:
    context-path: /${spring.application.name}
  shutdown: graceful

spring:
  application:
    name: person-management-service
  datasource:
    url: ${DB_JDBC_URL:jdbc:postgresql://localhost:5432/person-management}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin}

management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
  endpoint:
    info:
      enabled: true
    health:
      probes:
        enabled: true
