name: Build and Publish

on:
  push:
    branches:
      - main

concurrency:
  group: ci-bp-${{ github.ref }}

env:
  FE_IMAGE: docker.io/mandlon/show-case-ui
  BE_IMAGE: docker.io/mandlon/person-management-service

jobs:
  build-publish-frontend:
    runs-on: ubuntu-latest
    env:
      working-directory: ./show-case-ui
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Determine Docker Tag
        run: echo "DOCKER_TAG=$(node -e "console.log(require('./package.json').version);")-$GITHUB_SHA"  >> $GITHUB_ENV
        working-directory: ${{env.working-directory}}
      - name: Build Image
        run: docker build --tag "$FE_IMAGE:$DOCKER_TAG" .
        working-directory: ${{env.working-directory}}
      - name: Publish Image
        run: docker push "$FE_IMAGE:$DOCKER_TAG"
        working-directory: ${{env.working-directory}}
  build-publish-backend:
    runs-on: ubuntu-latest
    env:
      working-directory: ./person-management-service
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Determine Docker Tag
        run: echo "DOCKER_TAG=$(mvn -f pom.xml org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.version -q -DforceStdout)-$GITHUB_SHA" >> $GITHUB_ENV
        working-directory: ${{env.working-directory}}
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build Image
        run: mvn package -PbuildDocker -DskipTests -Ddocker.image.tag=$DOCKER_TAG
        working-directory: ${{env.working-directory}}
      - name: Publish Image
        run: docker push "$BE_IMAGE:$DOCKER_TAG"
        working-directory: ${{env.working-directory}}
