name: Build and Publish

on: [ pull_request ]

concurrency:
  group: ci-bp-${{ github.ref }}

env:
  IMAGE: docker.io/mandlon/show-case-ui

jobs:
  build-publish-frontend:
    runs-on: ubuntu-latest
    env:
      working-directory: ./show-case-ui
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Determine Docker Tag
        run: echo "DOCKER_TAG=$(node -e "console.log(require('./package.json').version);")-${{ github.run_number }}-$GITHUB_SHA"  >> $GITHUB_ENV
        working-directory: ${{env.working-directory}}
      - name: Build Image
        run: docker build --tag "$IMAGE:$DOCKER_TAG" .
        working-directory: ${{env.working-directory}}
      - name: Publish Image
        run: docker push "$IMAGE:$DOCKER_TAG"
        working-directory: ${{env.working-directory}}
