name: Build and test

on: [ pull_request ]

concurrency:
  group: ci-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build-and-test-frontend:
    runs-on: ubuntu-latest
    env:
      working-directory: ./show-case-ui
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'
      - run: npm install
        working-directory: ${{env.working-directory}}
      - run: npm run check-formatting
        working-directory: ${{env.working-directory}}
      - run: npm run build
        working-directory: ${{env.working-directory}}
