name: Build and test

on: [ pull_request ]

concurrency:
  group: ci-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build-and-test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./show-case-ui
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'
      - run: npm install
      - run: npm run check-formatting
      - run: npm run build
